Feature/lists exercises
ya-pekatoros/ru-study-python pull request #2
Opened 2023-02-24 09:40 UTC by ya-pekatoros

2023-02-26 20:54 UTC, aleksandr-semenov-dbp requested changes

2023-02-26 20:54 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            middle_index = round(len(input_list) / 2)
как насчет целочисленной операции //

2023-02-26 20:54 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +            if elem_subindex == -1:
проверка не имеет особого смысла, все равно возвращаешь elem_subindex

2023-02-27 01:13 UTC, ya-pekatoros commented on lists/lists.py
> +            middle_index = round(len(input_list) / 2)
Так редко пользуюсь, что даже не подумал, исправил, спасибо!

2023-02-27 01:15 UTC, ya-pekatoros commented on lists/lists.py
> +            if elem_subindex == -1:
Согласен, спасибо!

2023-02-28 12:00 UTC, aleksandr-semenov-dbp approved these changes

2023-02-28 14:12 UTC, merged