Add "filter_map" function
ya-pekatoros/ru-study-python pull request #4
Opened 2023-02-24 10:49 UTC by ya-pekatoros

2023-02-26 20:56 UTC, aleksandr-semenov-dbp requested changes

2023-02-26 20:56 UTC, aleksandr-semenov-dbp commented on filter_map/filter_map.py
> +        return list([result for cond, result in map(func, input_array) if cond])
а зачем вызов list()?

2023-02-27 01:22 UTC, ya-pekatoros commented on filter_map/filter_map.py
> +        return list([result for cond, result in map(func, input_array) if cond])
Действительно) спасибо, исправил!

2023-03-04 09:48 UTC, aleksandr-semenov-dbp approved these changes

2023-03-04 11:19 UTC, merged