Add "rating" and "chars_count" functions
ya-pekatoros/ru-study-python pull request #5
Opened 2023-02-24 13:06 UTC by ya-pekatoros

2023-02-26 20:59 UTC, aleksandr-semenov-dbp requested changes

2023-02-26 20:59 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +            if len(movie["country"].split(",")) > 1:
неэффективно использовать split() для подсчета запятых

2023-02-26 20:59 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +            for letter in movie["name"]:
так тоже неэффективно, у строк есть count()

2023-02-27 01:27 UTC, ya-pekatoros commented on maps/maps.py
> +            if len(movie["country"].split(",")) > 1:
Здесь скорее действовал из логики преобразовать исходную строку в понятную структуру, но т.к. это далее никак не используется да и структура даже не создается у меня - согласен, спасибо! Исправил.

2023-02-27 01:28 UTC, ya-pekatoros commented on maps/maps.py
> +            for letter in movie["name"]:
Забыл про него, спасибо! Исправил.

2023-03-04 09:47 UTC, aleksandr-semenov-dbp approved these changes

2023-03-04 11:19 UTC, merged