Add flask routes for user and user/<name>
ya-pekatoros/ru-study-python pull request #6
Opened 2023-02-25 01:52 UTC by ya-pekatoros

2023-02-26 21:08 UTC, aleksandr-semenov-dbp requested changes

2023-02-26 21:08 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +        @app.route("/user/<name>", methods=["GET", "PATCH", "DELETE"])
какой смысл объединять глаголы внутри одной функции, а в ней разделять их if-ами? Лишний отступ и худшая читаемость

2023-02-27 01:07 UTC, ya-pekatoros commented on flask_exercises/flask_excercises.py
> +        @app.route("/user/<name>", methods=["GET", "PATCH", "DELETE"])
Действительно, здесь нет никакой общей логики у функций, разделил, спасибо!

2023-03-04 09:49 UTC, aleksandr-semenov-dbp approved these changes

2023-03-04 11:20 UTC, merged